# Generated by Django 3.1.3 on 2020-11-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, verbose_name='name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_adult', models.BooleanField(verbose_name='adult')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(verbose_name='date')),
                ('opinion', models.TextField(max_length=200, verbose_name='feedback')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.user')),
            ],
        ),
    ]
