# Generated by Django 3.1.3 on 2020-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
