# Generated by Django 3.1.3 on 2020-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20201122_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='opinion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='feedback'),
        ),
    ]
